### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by SangYoung74** [jmont-dev/ollama-hpp#1]
In singleheader file(ollama.hpp)

1. this->cli = new httplib::Client(url);

2,
template <class T, class... Args>
typename std::enable_if<!std::is_array<T>::value, std::unique_ptr<T>>::type
make_unique(Args &&...args) {
  **return std::unique_ptr<T>(new T(std::forward<Args>(args)...));**
}

etc....
Many memory leak detected.

**Comment by jmont-dev** [comment]
Thanks for pointing this out. This single-header file combines several upstream libraries. This section is from cpp-httplib: https://github.com/yhirose/cpp-httplib

I'd recommend making an issue on their tracker and pointing out the memory leak so they can fix it upstream, then I'll pull down their changes.

**Comment by SangYoung74** [comment]
Thanks for reply.
The solution I found is:

======== Original code start (line 35159)========
public:
 Ollama(const std::string& url)
        {
            this->server_url = url;
            this->cli = new httplib::Client(url);
            this->setReadTimeout(120);
        }

        Ollama(): Ollama("http://localhost:11434") {}
        ~Ollama() {}

private:
httplib::Client* cli;
======== Original code end========

========= My fix code start ===========
Ollama(const std::string& url)
{
	delete this->cli; //add
	this->cli = nullptr; /add

	this->server_url = url;
	this->cli = new httplib::Client(url);
	this->setReadTimeout(120);
}
Ollama() : Ollama("http://localhost:11434") {}
~Ollama()
{
	delete this->cli; //add
	this->cli = nullptr; //add
}

private:
httplib::Client* cli = nullptr; //modify
========= My fix code end ==========
I don't know if it's a perfect solution, but it doesn't seem to have any problems in my test code.


========= My test code start ==========
Ollama my_server("http://localhost:11434");
ollama::response answer(my_server.generate("llama3.1:8b", "Why is the sky blue? Answer in korean"));
wstring strResultW = (wstring)CA2W(answer.as_simple_string().c_str(), CP_UTF8);
string strResultA = (string)CW2A(strResultW.c_str());
cout << strResultA << endl;
========= My test code end ==========

**Comment by jmont-dev** [comment]
You're right that a delete was missing from the destructor for the Ollama base class for the httplib instance that was allocated on the heap. I've added this via #4 and incorporated it into the main branch. Thanks again for your feedback.

**Comment by jmont-dev** [comment]
Closing this out as deletion of httplib is now occurring in the ollama destructor. If there are still issues with memory leaks in httplib please push these up to the base library at https://github.com/yhirose/cpp-httplib and we can pull them from upstream once they're resolved.

I will profile memory usage during my own testing and see if a leak is still occurring in any of the base libraries.
