### ISSUE TITLE
Should we be having single header?

### ISSUE THREAD

**Issue by JG-Adams** [jmont-dev/ollama-hpp#19]
I really appreciate this library and wants it to get better.
But, what are we having duplicated place for?
Trying to navigate and make change in single header is pretty rough considering the enormous amount of lines.
I think it's evidence that we'll be making a lot of changes. And this would only slow us down.
Not to mention the confusion it could make, if we ever forget to properly update both places.

**Comment by jmont-dev** [comment]
The single header include is very valuable for getting people up and running quickly. When doing development, you don't need to edit both files every time you make a change. Use the script `make_single_header.sh` in the main directory and it will automatically regenerate the single header version with the changes you make in the standard ollama.hpp. The single header version is not designed to be edited by hand.

**Comment by JG-Adams** [comment]
That make sense.
